# ChatPatch default config.yml
filter:
  - macs
  - osx
  - macintosh
  - whoop
  - mac
  - steve jobs
  - apple
  - apples
  - iphones
  - iphone
  - ipads
  - ipods
  - idevice
  - ipad
  - ipod
  - idevices
  
censored:
  - 069a79f4-44e9-4726-a5be-fca90e38aaf5 #Notch's UUID